name = "skland-attendance-cfworker"
main = "src/worker.ts"
compatibility_date = "2023-10-25"

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
crons = ["* * * * *"] # * * * * * = run every minute
